spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/haedal?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true # ?? ??? ?? schema ? ?? ?? ??
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always                      # Spring Boot >=v2.5.0


  logging:
    level:
      root: info
      com.zaxxer.hikari.HikariConfig: debug
      org.hibernate.SQL: trace
      hibernate.type.descriptor.sql.BasicBinder: trace
      org.hibernate.type.descriptor.sql: trace
  security:
    user:
      name: admin
      password: 1234
    oauth2:
      client:
        registration:
          kakao:
            client-id: b5d91872e5fa2c8c0a684e8f5c696e16
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret-key: heada-health.headal_health_2023_secret_key
  # 30 days
  token.expired-time-ms: 25920000