server:
  port: ${port:8081}
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: mysql://haedal-health-user:sqSMwrhV0cP3@srv-captain--bvpkftcsuw-mysql-80x:3306/haedal-health-database
    username: haedal-health-user
    password: sqSMwrhV0cP3
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      root: info
      com.zaxxer.hikari.HikariConfig: debug
      org.hibernate.SQL: debug
      hibernate.type.descriptor.sql.BasicBinder: trace

