server:
  port: ${port:3000}
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://srv-captain--bvpkftcsuw/haedal?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true # ?? ??? ?? schema ? ?? ?? ??
    username: haedal-health-user
    password: sqSMwrhV0cP3
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      root: info
      com.zaxxer.hikari.HikariConfig: debug
      org.hibernate.SQL: debug
      hibernate.type.descriptor.sql.BasicBinder: trace

