
server:
  port: 3000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: haedal-health-user
    password: uaLTtGj7xp31
    driver-class-name: com.mysql.cj.jdbc.Driver
  logging:
    level:
      root: info
      com.zaxxer.hikari.HikariConfig: debug
      org.hibernate.SQL: debug
      hibernate.type.descriptor.sql.BasicBinder: trace
